package com.luizmatias.todoapp.android.ui.theme

import androidx.compose.ui.graphics.Color

val md_theme_light_primary = Color(0xFF874395)
val md_theme_light_onPrimary = Color(0xFFffffff)
val md_theme_light_primaryContainer = Color(0xFFffd6ff)
val md_theme_light_onPrimaryContainer = Color(0xFF340043)
val md_theme_light_secondary = Color(0xFF6b596c)
val md_theme_light_onSecondary = Color(0xFFffffff)
val md_theme_light_secondaryContainer = Color(0xFFf3dbf2)
val md_theme_light_onSecondaryContainer = Color(0xFF241726)
val md_theme_light_tertiary = Color(0xFF82524c)
val md_theme_light_onTertiary = Color(0xFFffffff)
val md_theme_light_tertiaryContainer = Color(0xFFffdad4)
val md_theme_light_onTertiaryContainer = Color(0xFF33110d)
val md_theme_light_error = Color(0xFFba1b1b)
val md_theme_light_errorContainer = Color(0xFFffdad4)
val md_theme_light_onError = Color(0xFFffffff)
val md_theme_light_onErrorContainer = Color(0xFF410001)
val md_theme_light_background = Color(0xFFfcfcfc)
val md_theme_light_onBackground = Color(0xFF1e1a1e)
val md_theme_light_surface = Color(0xFFfcfcfc)
val md_theme_light_onSurface = Color(0xFF1e1a1e)
val md_theme_light_surfaceVariant = Color(0xFFecdee9)
val md_theme_light_onSurfaceVariant = Color(0xFF4d444c)
val md_theme_light_outline = Color(0xFF7e747d)
val md_theme_light_inverseOnSurface = Color(0xFFf7eef3)
val md_theme_light_inverseSurface = Color(0xFF342f33)

val md_theme_dark_primary = Color(0xFFf7acff)
val md_theme_dark_onPrimary = Color(0xFF520e62)
val md_theme_dark_primaryContainer = Color(0xFF6c2a7b)
val md_theme_dark_onPrimaryContainer = Color(0xFFffd6ff)
val md_theme_dark_secondary = Color(0xFFd7c0d6)
val md_theme_dark_onSecondary = Color(0xFF3a2b3c)
val md_theme_dark_secondaryContainer = Color(0xFF524253)
val md_theme_dark_onSecondaryContainer = Color(0xFFf3dbf2)
val md_theme_dark_tertiary = Color(0xFFf6b8b0)
val md_theme_dark_onTertiary = Color(0xFF4c2521)
val md_theme_dark_tertiaryContainer = Color(0xFF663b36)
val md_theme_dark_onTertiaryContainer = Color(0xFFffdad4)
val md_theme_dark_error = Color(0xFFffb4a9)
val md_theme_dark_errorContainer = Color(0xFF930006)
val md_theme_dark_onError = Color(0xFF680003)
val md_theme_dark_onErrorContainer = Color(0xFFffdad4)
val md_theme_dark_background = Color(0xFF1e1a1e)
val md_theme_dark_onBackground = Color(0xFFe8e0e4)
val md_theme_dark_surface = Color(0xFF1e1a1e)
val md_theme_dark_onSurface = Color(0xFFe8e0e4)
val md_theme_dark_surfaceVariant = Color(0xFF4d444c)
val md_theme_dark_onSurfaceVariant = Color(0xFFcfc3cc)
val md_theme_dark_outline = Color(0xFF988d96)
val md_theme_dark_inverseOnSurface = Color(0xFF1e1a1e)
val md_theme_dark_inverseSurface = Color(0xFFe8e0e4)

val seed = Color(0xFF9651a4)
val error = Color(0xFFba1b1b)